lag: 0
ub_stock: 2
ub_delay: 10
ub_terms: 10
window: 10
eval_window: 100
Ntraders: 100
q: 0.5
pmax: 1
target: LogReturn

uselist: B
whitelist:
    stocks:
        - INDEX
        - AAPL
        - BAC
        - TSLA
        - AMZN
        - GOOGL
        - GOOG
        - F
        - NVDA
        - AMD
        - T
        - MSFT
        - INTC
        - PFE
        - CSCO
        - META
        - MU
        - C
        - WFC
        - CMCSA
        - HPQ
blacklist:
    stocks:

